version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: sake.sh
      LETSENCRYPT_HOST: sake.sh
      PORT: 80
      GIT_ROOT: /git
      APP_ID: ${APP_ID}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      PRIVATE_KEY: ${PRIVATE_KEY}
      DEBUG: sake
    volumes:
      - ./data:/git

networks:
  default:
    name: webproxy
    external: true
